version: '3'
services:
  transfersh:
    build: ./transfer.sh
    image: transfersh:schniggie
    ports:
      - 8081:8080 # Unsecured HTTP Web Port
    volumes:
      - transfersh-data:/tmp
    command:
      - "--provider=local"
      - "--basedir=/tmp"

  nifi:
    image: apache/nifi:latest
    ports:
      - 8082:8082 # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8082
      - NIFI_ELECTION_MAX_WAIT=1 min

volumes:
  transfersh-data:
